# Generated by Django 4.0.3 on 2022-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[(None, '(unknown)'), ('movie', 'movie'), ('tv_show', 'tv_show')], default='movie', max_length=15, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[(None, '(unknown)'), ('actor', 'actor'), ('director', 'director'), ('writer', 'writer')], max_length=15, null=True, verbose_name='role'),
        ),
    ]
