version: "3.9"

services:
  web:
    build: ./app
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - web-static:/app/static
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${WEB_KEY}
    depends_on:
      - postgres
    #command: gunicorn --bind 0.0.0.0:8000 config.wsgi
    command: python3 manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_site
        target: /etc/nginx/conf.d/site.conf

  postgres:
    build: ./db
    image: psql
    expose:
      - ${DB_PORT}
    ports:
      - "127.0.0.1:5000:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web-static:
  pgdata:

configs:
  nginx_conf:
    file: ./nginx/nginx.conf
  nginx_site:
    file: ./nginx/site.conf
